name: Deploy Images to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  RELEASE_VERSION: ${{ date('yyyyMMdd') }}
  
jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Release Version
      run: echo "Release Version is ${{ env.RELEASE_VERSION }}"
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/wowmarcomei/opengauss-prometheus-exporter:${{ env.RELEASE_VERSION }}
