name: Deploy Images to GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set env
      run: echo "RELEASE_VERSION=${{ steps.date.outputs.date }}" >> $GITHUB_ENV
      id: date
      env:
        TZ: Asia/Shanghai
      shell: bash
      
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/wowmarcomei/opengauss-prometheus-exporter:${{ env.RELEASE_VERSION }}
